### ISSUE TITLE
Re-start AppVeyor

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/udunits2-feedstock#1]
https://github.com/conda-forge/conda-forge.github.io/issues/35

**Comment by pelson** [comment]
Should be doing its thing.

**Comment by ocefpaf** [comment]
Yep. Closing this.

(See https://ci.appveyor.com/project/conda-forge/udunits2-feedstock/branch/master)

**Comment by pelson** [comment]
@ocefpaf - do you have the power to cancel builds etc.?

**Comment by ocefpaf** [comment]
> @ocefpaf - do you have the power to cancel builds etc.?

Nope.  But now I can view the build log from master (that was not possible before.)

**Comment by pelson** [comment]
> Nope. But now I can view the build log from master (that was not possible before.)

Ok. That is an improvement. You are listed as an administrator on the conda-forge user (and should be able to log in as such when logging in to appveyor?). We should screen share sometime next week and I'll show you what I see.

Thanks!

**Comment by ocefpaf** [comment]
> We should screen share sometime next week and I'll show you what I see.

I got it by logging out and logging in again. (But I could not find a way to change accounts or access both once logged into one.)

**Comment by pelson** [comment]
> (But I could not find a way to change accounts or access both once logged into one.)

Horrific isn't it. :disappointed:

**Comment by ocefpaf** [comment]
> Horrific isn't it. :disappointed:

`AppVeyor` is far behind `Travis-CI` and `CircleCI`, but hey... It exists!

(I heard some stories about people building packages using Linux+wine. Wanna go that route? :wink:)
