### ISSUE TITLE
Default XML path not working on Windows

### ISSUE THREAD

**Issue by pelson** [conda-forge/udunits2-feedstock#18]
As seen in https://github.com/SciTools/cf_units/issues/107, udunits does not correctly work with the default XML path baked into the binary.

We don't test this in the build, because the test defined in meta.yaml is ```udunits2 -H meter -W miles  # [not win]```

I notice that there is also paths such as ```UDUNITS2_XML_PATHC:\bld\udunits2_1520456853802\_b_env\Library\share\udunits\udunits2.xml``` in the conda-forge udunits ``udunits2.dll``, which should really be replaced by conda install. This suggests we need to update the recipe to do correct binary replacement.

**Comment by pelson** [comment]
Does conda-build not have the facilities to replace arbitrary prefixes in binaries (for windows?). I seem to recall that this wasn't implemented a few years ago, and looks like that may still be the case today...

**Comment by pelson** [comment]
https://stackoverflow.com/a/15076555/741316 suggests it is at least sensible to do this with ``.dll``s. Now just need to figure out if the machinery already exists in conda-build..

**Comment by pelson** [comment]
Really helpful hint from @mingwandroid regarding the Windows patch that anaconda apply: https://github.com/conda/conda-build/issues/2207#issuecomment-390931702

Personally, I'm against this approach, but am completely comfortable to be overruled...

**Comment by mingwandroid** [comment]
Can you detail why you are against this approach?

Modifying binaries is a complete no-no to me personally. It changes the checksums and prevents the binary from being signed and is thus a security disaster.

**Comment by pelson** [comment]
Thanks @mingwandroid. Useful insight.

> It changes the checksums and prevents the binary from being signed and is thus a security disaster.

conda is well in the world of replacing prefixes in files (binary or otherwise). Does binary replacement at build/install time differ in any way to prefix replacement from a signing perspective (I'm very naive in the way singing has been implemented in conda)? Is there a reason that dll can't be signed after it has been modified (e.g. https://stackoverflow.com/a/33758901/741316)?

> Can you detail why you are against this approach?

Essentially, udunits2 is being forked in https://github.com/AnacondaRecipes/udunits2-feedstock/blob/master/recipe/0002-Use-the-shared-library-to-locate-the-default-xml.patch. The code that users are getting when they use "udunits2" in anaconda is not the code that is available at https://github.com/Unidata/UDUNITS-2. Conversely, patching the binary is not forking the package and is instead about working around the details of the packaging system being used to deploy/install it.

This sense of "forking udunits2" is strengthened by the fact that there appears to be no outstanding request to integrate the changes back up to the udunits2 repository.

**Comment by mingwandroid** [comment]
> conda is well in the world of replacing prefixes in files (binary or otherwise).

That doesn't make it a good idea.

> Is there a reason that dll can't be signed after it has been modified

You cannot sign a binary post modification on an end user's computer without them having *your* private signing key.

Essentially, udunits2 is being forked in https://github.com/AnacondaRecipes/udunits2-feedstock/blob/master/recipe/0002-Use-the-shared-library-to-locate-the-default-xml.patch. The code that users are getting when they use "udunits2" in anaconda is not the code that is available at https://github.com/Unidata/UDUNITS-2. Conversely, patching the binary is not forking the package and is instead about working around the details of the packaging system being used to deploy/install it.

I disagree with your assertion that patching software makes it less of a fork than patching a binary. At least one is scrutable by looking at the patch to the source code. Have you studied the construction of any linux distribution? They all carry numerous patches for issues not addressed upstream. I don't really care for the linguistic arguments about what does and does not constitute a fork though.
I do agree that the patches should be suggested to upstream though clearly.

**Comment by mingwandroid** [comment]
Finally, while I've got your attention, have you ever tried to upstream a patchset as large (and necessary) but of no interest to upstream as for example https://github.com/AnacondaRecipes/qt-feedstock/tree/master/recipe

Take it from me, life is too short.

**Comment by mingwandroid** [comment]
Finally finally, how *exactly*, would you binary patch the following code:

```
int main(int argc, char * argv[]) {
  std::string prefix = "C:\Users\rdonnelly\m64\conda-bld\udunits2";
}
```

.. it is not possible without changing the software as follows:

```
static volatile prefix_c[MAX_PATH]="C:\Users\rdonnelly\m64\conda-bld\udunits2";
int main(int argc, char * argv[]) {
  std::string prefix(prefix_c);
}
```

Is that patch now acceptable?

**Comment by pelson** [comment]
> Is that patch now acceptable?

Still no, IMO.

> Have you studied the construction of any linux distribution? They all carry numerous patches for issues not addressed upstream.

That doesn't make it a good idea. 😜 

> Take it from me, life is too short.

I completely agree with this statement. I was hinting at this in my [comment](https://github.com/conda/conda-build/issues/2207#issuecomment-390935512) relating to the fact that we are "we're working to different objectives". I appreciate that as a regular conda-forge contributor and a developer on Anaconda you wear two hats. The Anaconda makes its money from making this stuff "just work", whereas conda-forge is here to package whatever the package owner produces (whether it is 💩 or not). The only rub for conda-forge is that it needs to take into account the medium over which it is deploying its packages (conda) - there is no other motivator for conda-forge to make stuff "just work", all that motivation is deferred down to the package authors, who probably (we hope) want to improve their software in order to get it working in the conda-forge distribution. 

Let's draw this conversation to a close. I really appreciate you're perspective on this, and am quite comfortable that we can disagree robustly and healthily 👍.

In this instance, I'm OK with pushing this issue back to the upstream authors and offer to give support and pointers should they need it. I also appreciate that, as you say, for some packages that just isn't worth the effort - the only real difference between our perspectives is what we do with the "isn't worth the effort". In Anaconda's case, you are motivated to make it "just work", in conda-forge I'm motivated to not bother with the software (or more likely, push the issue upstream, perhaps even helping them to fix the issue if I *really* want the software).

**Comment by mingwandroid** [comment]
Thanks @pelson, I'd rather be direct than skirt around issues here .. before we close this out let me give my complete perspective.

>> Is that patch now acceptable?

> Still no, IMO.

My point with this `std:string` example is to show that there are many (and increasingly more as modern C++ takes further hold) cases where binary prefix replacement cannot be used as it does not work. This is an example. So if you have (and we have several) an upstream that contains such code there is no option *but* to modify the software. Is this clear? Do you see any alternative? What would you do here to make this software available to conda-forge users?

> isn't worth the effort

I need to clarify this too, I don't mean that I am lazy here or that I like rebasing patches at new releases, far from it. If I could divest myself of all patches I honestly would *but* there are specific points of difference between how we (AD and conda-forge) do software vs the rest of the world and upstreams. Apart from binary prefix replacement (which I'd seek to eliminate entirely) we support old Linux and macOS distros as well as old compilers on Windows when upstreams explicitly do not. Providing this support *requires* removing calls to APIs not available in the old versions, but since upstream are "macOS 10.11, glibc 2.17 or above only" we are left with no choice *but* to carry local patches. That is what I mean by not worth the effort, they will literally say "no" and with good reason too, they do not want this legacy cruft in their codebases.

If you are happy to work through a CEP on a policy around patching in general (when it is acceptable and when it is not) and another around binary prefix replacement I am happy to try to help out.

I will try to upstream this one to UDUNITS-2.

**Comment by pelson** [comment]
> So if you have (and we have several) an upstream that contains such code there is no option but to modify the software. Is this clear? Do you see any alternative? What would you do here to make this software available to conda-forge users?

I see the dilemma, and recognise that it is particularly acute for AD. Honestly, from c-f perspective, I'd be pushing quite hard to avoid packing the tool altogether. A good example of this is the python-eccodes package, which has no released python 3 support: the patch is pretty trivial, and is even part of Debian, but not something that I support in conda-forge. I do also appreciate that the horse has bolted in a lot of cases even on conda-forge - and that certainly not everybody (perhaps nobody) else in conda-forge shares my outlook. Even from my ivory tower I've been known to be in conflict with the (probably over-)strong opinions I've expressed in this thread.

> we support old Linux and macOS distros as well as old compilers on Windows when upstreams explicitly do not

Agreed. The idea of **never** patching is frankly idealistic and highly unrealistic. In these situations, I do agree with patching. Unfortunately there is a very grey line between "supporting old compilers" and "making the tool work with conda".

Your idea of a CEP that lays out some guidelines around patching is a good one, and even though I've clearly got an opinion 😉, I suspect I'm not the kind of detail focussed person that is best suited to lead on such a thing (one of the reasons that c-f on the whole doesn't have a particularly strong history of policy statements IMO).

> I will try to upstream this one to UDUNITS-2.

Much obliged.

**Comment by mingwandroid** [comment]
> I see the dilemma, and recognise that it is particularly acute for AD. Honestly, from c-f perspective, I'd be pushing quite hard to avoid packing the tool altogether

I think it's the same for CF and AD here. To make it more acute for all, replace "tool" with "very important core library". You are effectively saying "no projects that are written in C++11 and beyond here that require relocation if upstream won't accept a dynamic relocation patch".  That would be very restrictive. Worse, if a project converted from C++98 to C++11 you'd end up in a position where you cannot update to the new version, leaving users vulnerable to any security issues in the older version.

Cheers!

**Comment by zklaus** [comment]
I think this is resolved by now. Since @pelson has moved on to greener pastures, @ocefpaf, do you have an opinion on this?

**Comment by ocefpaf** [comment]
> I think this is resolved by now. Since @pelson has moved on to greener pastures, @ocefpaf, do you have an opinion on this?

Let me test this tomorrow on a Windows machine. In the past the tests passed but some odd things happened in the installed package, specially when change drives on Windows (installation in one drive but running the code in another, very odd).

**Comment by zklaus** [comment]
@xylar's PR (#41) drove me back to this repo.

@ocefpaf, did anything ever come of your windows experiment? Or could it be that we also need an activation script for windows?

**Comment by xylar** [comment]
@zklaus, there is an activation script for windows: https://github.com/conda-forge/udunits2-feedstock/blob/master/recipe/scripts/activate.bat

It was added in https://github.com/conda-forge/udunits2-feedstock/pull/19 on May 22, 2018, so the same day that the major traffic on this issue occurred.  Presumably it was intended to address the issue.  My guess would be that the issue simply didn't get closed.  Probably it could be closed for now and re-opened if #19 turns out not to have addressed it, unless @ocefpaf has a quick way to test.

**Comment by ocefpaf** [comment]
> unless @ocefpaf has a quick way to test.

Nope. I no longer have a Windows laptop, stolen with my cellphone. Which lead to some really terrible consequences as https://github.com/pypa/pypi-support/issues/1201 :unamused: 

Let's close and open a new one if folks are still experiencing this.

**Comment by xylar** [comment]
Oh, no!  Sounds miserable!
