### ISSUE TITLE
activation scripts needed for csh/tcsh

### ISSUE THREAD

**Issue by xylar** [conda-forge/udunits2-feedstock#30]
This is mostly a note to myself to add activation scripts for other shells.  See https://github.com/conda-forge/nco-feedstock/issues/103, where the lack thereof caused problems.

**Comment by czender** [comment]
We're not sure yet, but this issue may be related to recent failure in e3sm_to_cmip documented here: https://github.com/E3SM-Project/e3sm_to_cmip/pull/83
