### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by zklaus** [conda-forge/udunits2-feedstock#36]
Issue: Some new releases of udunits2 are available. Specifically, I need to be able to format timeunits including "since 2001-01-01 00:00:00", something that was added in Unidata/UDUNITS-2@3e607e13e8964e21e358690fa87b5e8a03b140e1 and released in version 2.2.27.15 (Unidata/UDUNITS-2@a710228a8a02d46e8058507487b33299cc1de7cf). Of course, an update to the most recent version seems sensible.

I am happy to work on this; since there is already a corresponding bot PR, it would probably make sense to join the team before starting on it. Or do you prefer a PR against the open PR?

ping @conda-forge/udunits2

**Comment by ocefpaf** [comment]
No need to use the open PR. Those are probably quite stale. If you know how to fix our builds please send a fresh PR and add yourself to the team! Thanks!!
